package controlers;


public class KeyTable {
    final public static String
            TIDLE = "~",
            ONE = "1",
            TWO = "2",
            THREE = "3",
            FOUR = "4",
            FIVE = "5",
            SIX = "6",
            SEVEN = "7",
            EIGHT = "8",
            NINE = "9",
            ZERO = "0",
            MINUS = "-",
            EQUAL = "=",
            BACKSPACE = "backspace",
            TAB = "tab",
            Q = "q",
            W = "w",
            E = "e",
            R = "r",
            T = "t",
            Y = "y",
            U = "u",
            I = "i",
            O = "o",
            P = "p",
            LEFT_BRACKET = "[",
            RIGHT_BRACKET = "]",
            BACKSLASH = "\\",
            CAPS_LOCK = "capsLock",
            A = "a",
            S = "s",
            D = "d",
            F = "f",
            G = "g",
            H = "h",
            J = "j",
            K = "k",
            L = "l",
            SEMI_COLON = ";",
            APOSTROPHE = "'",
            RETURN = "return",
            SHIFT = "shift",
            Z = "z",
            X = "x",
            C = "c",
            V = "v",
            B = "b",
            N = "n",
            M = "m",
            COMMA = ",",
            DOT = ".",
            SLASH = "/",
            UP_ARROW = "up",
            CTRL = "ctrl",
            WIN = "win",
            ALT = "alt",
            SPACE = "space",
            LEFT_ARROW = "left",
            DOWN_ARROW = "down",
            RIGHT_ARROW = "right";
}

